### ISSUE TITLE
ガチャ画面からブラウザバックするとガチャ選択画面に戻れない

### ISSUE THREAD

**Issue by newnakashima** [originbenntou/E-Lunch#3]
ガチャ画面からブラウザバックするとガチャ選択画面に戻れません。
これは仕様でしょうか？

**Comment by originbenntou** [comment]
@newnakashima 
お知らせありがとうございます。
ご指摘の内容は仕様ではありません。
順次対応しますので、対応完了しましたら改めてご連絡いたします

**Comment by newnakashima** [comment]
https://github.com/originbenntou/E-Lunch/pull/8
こんな感じでどうでしょう？？

**Comment by originbenntou** [comment]
ありがとうございました！
こちらクローズします🤕
